### ISSUE TITLE
Typescript errors are not highlighted in the editor

### ISSUE THREAD

**Issue by akondrasev** [stackblitz/core#2130]
Basically what the title says, do not see typescript errors in the editor.

**Comment by geromegrignon** [comment]
Hi @akondrasev, please provide a failing project example. Errors are displayed as expected for me.

**Comment by akondrasev** [comment]
Hello, thanks for the quick reply! Sorry I did not post it initially. 

Here is the [link](https://stackblitz.com/edit/prj-angular?file=src%2Fapp%2Fservice.ts) to my stackblitz angular project.

Since it is working so inconsistently I post the screenshots too as a prove:
![image](https://user-images.githubusercontent.com/9110254/198132592-e982a18a-ffbc-4e5b-b4a7-87a145397888.png)

![image](https://user-images.githubusercontent.com/9110254/198132749-a4be20ae-91d0-4582-83d6-6293f30141ae.png)

On the right side in demo space it shows only service error, however, in main.ts there should also be an error with index access of the ngRef property which does not exist on type Window.

**Comment by geromegrignon** [comment]
About the first issue, it sounds like a random bug, I'm able to reproduce it by copying the interface and options definition but not every time.
<img width="569" alt="image" src="https://user-images.githubusercontent.com/32737308/198145326-054d2282-4d65-4c73-8a84-27c9f60da64f.png">

About the second example, by using `['ngRef]` syntax, implies you are suggesting you know better.
Types aren't checked on such a syntax. That's why that's a bad practice to check types.

**Comment by akondrasev** [comment]
> Types aren't checked on such a syntax.
I am using "strict": true in tsconfig.json, it starts to check this syntax too with strict mode enabled. If i download my project and open in my IDE it would correctly display the error. 

![image](https://user-images.githubusercontent.com/9110254/198207625-62d78ace-ebbd-43e8-9bcc-01191e716734.png)

**Comment by geromegrignon** [comment]
Thanks for providing these details.
I'll let Stackblitz team gather it for a fix.
